### ISSUE TITLE
Consider CloudABI as the basis for the native API

### ISSUE THREAD

**Issue by lain-dono** [WebAssembly/reference-sysroot#4]
https://github.com/NuxiNL/cloudabi

I think that for most applications, this API (or similar) is sufficient. It was originally created to run native applications obtained from untrusted sources.

**Comment by sunfishcode** [comment]
I like this idea. And I think it highlights the fact that there won't be one set of syscalls which will apply to all use cases. Some use cases will want to use a restricted set, such as CloudABI, while others won't want to be restricted.

**Comment by lachlansneff** [comment]
I've been thinking about this as well. CloudABI's main issue is the need to specify files and sockets that it can open/access in a configuration file, which can be quite restricting (and also would completely kill any attempts to port language interpreters to wasm).

I foresee an API similar to POSIX that's designed to be run in lightweight containers or with whitelisted resources so that sandboxing is separate from the design of the API. And then go for an API similar to CloudABI if people would find it useful.

I think layering of APIs over time is a good idea though. We should attempt to get down the basic apis that don't really change much in use-case, like arguments and environment variables as soon as possible.

A CloudABI based system interface has a lot of progress, but I'm not sure it should be the first standardized api.

**Comment by syrusakbary** [comment]
CloudABI could be a great fit for WebAssembly, indeed.

We wrote more about it here: https://medium.com/wasmer/webassembly-cloudabi-b573047fd0a9
Might be useful for anyone looking to get deeper context on the field 😊

**Comment by sunfishcode** [comment]
I've been investigating CloudABI as [I mentioned above](https://github.com/WebAssembly/reference-sysroot/issues/4#issuecomment-444298550). CloudABI has a lot to offer, but isn't quite the right shape for WebAssembly. I also investigated the "PWSIX" concept (for background on that term, see Mozilla's blog post here)[https://hacks.mozilla.org/2018/10/webassemblys-post-mvp-future/], we found [there are significant parts of POSIX that don't fit well on WebAssembly](https://github.com/CraneStation/wasmtime-wasi/blob/wasi/docs/WASI-rationale.md), and so we believe that [WASI](https://github.com/WebAssembly/reference-sysroot/pull/11), which takes much inspiration from those systems, but is also tailored to WebAssembly's unique needs, is the best way forward.

**Comment by syrusakbary** [comment]
That sounds good. We will be adapting the Wasmer runtime to support WASI as well.

Great work there!

**Comment by sunfishcode** [comment]
The initial issue is now addressed. Please feel free to open new issues if there are any further questions or ideas here!
